config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  root to: "messages#index"
  resources :messages, only: :index
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baseball_history.rb
class BaseballHistory < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'メジャー'},
    { id: 3, name: 'NPB'},
    { id: 4, name: '社会人'},
    { id: 5, name: '大学'},
    { id: 6, name: '高校'},
    { id: 7, name: '中学校'},
    { id: 8, name: '小学校'},
    { id: 9, name: '未経験'},
  ]
include ActiveHash::Associations
has_many :users
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '投手'},
    { id: 3, name: '捕手'},
    { id: 4, name: '内野手'},
    { id: 5, name: '外野手'},
  ]

include ActiveHash::Associations
has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions  
  belongs_to :position  
  belongs_to :baseball_history
  has_many   :room_users
  has_many   :rooms, through: :romm_users
  has_many   :messages
  has_many   :posts
  has_one_attached :image

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password,    format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
    with_options format: {with: /\A[ぁ-んァ-ン一-龥々ー]+\z/ } do
      validates :last_name
      validates :first_name
    end
    validates :birthday
    validates :image
    with_options numericality: { other_than: 1 } do
      validates :position_id
      validates :baseball_history_id
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :nickname, :last_name, :first_name, :birthday, :position_id, :baseball_history_id])
  end    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BaseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
         <%= link_to image_tag("logo.png", class: :logo), root_path %>
      </div>
      <% if user_signed_in? %>
        <div class="nav__right"> 
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          <%= link_to current_user.nickname, user_path(current_user.id), class: :nav__btn %>
        </div> 
      <% else %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
        </div>
      <% end %>  
    </div>
  </div>
</header>
<main class="main">
  
</main>
<footer class="footer">
  <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
</footer>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class: "second-logo"), root_path %>
</header>

app/views/users/show.html.erb
<%= render "shared/second-header" %>
  <div class="registration">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <div class="item-img-content">
      <%= image_tag @user.image, class:"item-box-img" %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ポジション</th>
            <td class="table__col2"><%= @user.position.name %></td>
          </tr>
          <tr>
            <th class="table__col1">野球歴</th>
            <td class="table__col2"><%= @user.baseball_history.name %></td>
          </tr>
        </tbody>
      </table>
      <% if user_signed_in? %>
        <% if @user != current_user%>
          <%= link_to "メッセージを送る", root_path, class:"item-red-btn" %>
        <% end %>  
      <% end %>
    </div>
  </div>  